### ISSUE TITLE
Client is trying to send a message with only spaces

### ISSUE THREAD

**Issue by jdnss** [Flysend/issue-tracker#6]
kinda related to #3

https://github.com/user-attachments/assets/c9769256-1206-4773-9b6d-f6834cdf75cb

**Comment by w3lcharm** [comment]
да бляяяяять, опять фиксить

**Comment by crtmitchn** [comment]
яблучки яблучки шщшщшщшщшщшщ

**Comment by crtmitchn** [comment]
фикса не будет, воте сли гомяк выйдет на листинг, то я подумаю!!!!
![quote_1258105502416502897](https://github.com/user-attachments/assets/82474dfd-a3bc-43ae-a381-e4bad88391c2)

**Comment by w3lcharm** [comment]
никита блять ты чё творишь

**Comment by jdnss** [comment]
чё

**Comment by crtmitchn** [comment]
какой
